<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Infinite scroll</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='css/main.css'>
  

 
    <script src='js/main.js'></script>
</head>
<body>
        <h1 style="text-align: center;">INFINITE SCROLL</h1>
       <div id="timeline">
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               <div class="timeline"><p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Soluta, ipsa laborum! Aut doloremque, aspernatur, similique dolorem soluta quis sapiente dignissimos tenetur fuga cum, blanditiis a commodi totam itaque praesentium. Soluta?</p></div>
               
       </div>
</body>
</html>